/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.AlterarFuncionarioDAO;
import javax.swing.JOptionPane;
import model.FuncionarioVO;

/**
 *
 * @author guilherme-matte
 */
public class GUIAlterarFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAlterarFuncionario
     */
    public GUIAlterarFuncionario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNomeFuncionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbCargo = new javax.swing.JComboBox<>();
        jcbVA = new javax.swing.JCheckBox();
        jcbPlano = new javax.swing.JCheckBox();
        jcbVT = new javax.swing.JCheckBox();
        jbtAlterar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfSalario = new javax.swing.JTextField();
        jtfVT = new javax.swing.JTextField();
        jtfPlano = new javax.swing.JTextField();
        jtfVA = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALTERAR DADOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Matrícula");

        jtfMatricula.setEditable(false);
        jtfMatricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfMatricula.setEnabled(false);
        jtfMatricula.setRequestFocusEnabled(false);
        jtfMatricula.setVerifyInputWhenFocusTarget(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("NOME DO FUNCIONÁRIO");

        jtfNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("SALÁRIO DO FUNCIONARIO");

        jcbCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Estagiário", "Gerente" }));

        jcbVA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbVA.setText("VALE ALIMENTAÇÃO");
        jcbVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVAActionPerformed(evt);
            }
        });

        jcbPlano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbPlano.setText("PLANO DE SAÚDE");
        jcbPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPlanoActionPerformed(evt);
            }
        });

        jcbVT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbVT.setText("VALE TRANSPORTE");
        jcbVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVTActionPerformed(evt);
            }
        });

        jbtAlterar.setText("ALTERAR");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });

        jbtLimpar.setText("LIMPAR");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("CARGO DO FUNCIONÁRIO");

        jtfVT.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jtfVT.setEnabled(false);

        jtfPlano.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jtfPlano.setEnabled(false);

        jtfVA.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jtfVA.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbPlano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbVT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfVA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPlano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jtfVT))
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addComponent(jbtAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfNomeFuncionario)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtfSalario)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfNomeFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfVT)
                    .addComponent(jcbVT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbPlano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void preencherCamposGAF(String id) {
        jtfMatricula.setText(id);
        AlterarFuncionarioDAO aDAO = new AlterarFuncionarioDAO();
        FuncionarioVO fVO = new FuncionarioVO();

        try {

            fVO = aDAO.PreencherCamposFuncinario(id);

            jtfNomeFuncionario.setText(fVO.getNome());
            jtfSalario.setText(String.valueOf(fVO.getSalario()));
            
            if (fVO.getPlano() > 0 ) {
                jcbPlano.set;
                jtfPlano.setEnabled(true);
                jtfPlano.setText(String.valueOf(fVO.getPlano()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO - " + e.getMessage());
        }
    }

    public void alterarFuncionario() {

    }

    private void jcbVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVAActionPerformed
        if (jcbVA.isSelected()) {
            jtfVA.setEnabled(true);
        } else {
            jtfVA.setEnabled(false);

        }
        jtfVA.setText(null);
    }//GEN-LAST:event_jcbVAActionPerformed

    private void jcbPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPlanoActionPerformed
        if (jcbPlano.isSelected()) {
            jtfPlano.setEnabled(true);
        } else {
            jtfPlano.setEnabled(false);

        }
    }//GEN-LAST:event_jcbPlanoActionPerformed

    private void jcbVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVTActionPerformed
        if (jcbVT.isSelected()) {
            jtfVT.setEnabled(true);
        } else {
            jtfVT.setEnabled(false);
        }
        jtfVT.setText(null);
    }//GEN-LAST:event_jcbVTActionPerformed
    public void limparCampos() {
        jtfNomeFuncionario.setText("");
        jtfPlano.setText("");
        jtfPlano.setEnabled(false);
        jtfSalario.setText("");
        jtfVA.setText("");
        jtfVA.setEnabled(false);
        jtfVT.setText("");
        jtfVT.setEnabled(false);
        jcbCargo.setSelectedIndex(0);
        jcbPlano.setSelected(false);
        jcbVA.setSelected(false);
        jcbVT.setSelected(false);

    }
    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed

        if (jcbVT.isSelected() && jtfVT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencha ou desabilite o campo vale transporte");
        } else if (jcbVA.isSelected() && jtfVA.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencha ou desabilite o campo vale alimentação");
        } else if (jcbPlano.isSelected() && jtfPlano.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencha ou desabilite o campo plano de saúde");
        } else {
            limparCampos();
        }

    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_jbtLimparActionPerformed
    public void abrirTela() {
        GUIAlterarFuncionario gaf = new GUIAlterarFuncionario();
        gaf.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JCheckBox jcbPlano;
    private javax.swing.JCheckBox jcbVA;
    private javax.swing.JCheckBox jcbVT;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfNomeFuncionario;
    private javax.swing.JTextField jtfPlano;
    private javax.swing.JTextField jtfSalario;
    private javax.swing.JTextField jtfVA;
    private javax.swing.JTextField jtfVT;
    // End of variables declaration//GEN-END:variables
}
