/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.ConEmpresaDAO;
import dao.ConPessoaFisicaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableModel;
import model.ProdutoEmpresaVO;
import model.ProdutoPessoaFisicaVO;
import static view.GUIPrincipal.jdpAreaDeTrabalho;

/**
 *
 * @author Admin
 */
public class GUIConsultarComputadores extends javax.swing.JInternalFrame implements InternalFrameListener {

    DefaultTableModel dtmEmpresa = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"ID Produto", "CNPJ", "Categoria", "Nome da Empresa", "Responsável", "Quantidade", "Descrição"}
    );

    DefaultTableModel dtmPessoaFisica = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"ID Produto", "CPF", "Nome Completo", "Quantidade","Categoria",  "Descrição"}
    );

    /**
     * Creates new form GUIConsultarComputadores
     */
    public GUIConsultarComputadores() {

        initComponents();
        PreencherTabelaEmpresas();
        PreencherTabelaPessoaFisica();
        jtbConsultaEmpresa.setModel(dtmEmpresa);
        jtbConsultaPF.setModel(dtmPessoaFisica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpConsulta = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbConsultaEmpresa = new javax.swing.JTable();
        jtfConsultaEmpresa = new javax.swing.JTextField();
        jcbConsultaEmpresa = new javax.swing.JComboBox<>();
        jbtAlterarEmpresa = new javax.swing.JButton();
        jbtAtualizarTabelaEmpresa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbConsultaPF = new javax.swing.JTable();
        jcbPesquisarConsultaPF = new javax.swing.JComboBox<>();
        jtfConsultaPF = new javax.swing.JTextField();
        jbtAlterarPF = new javax.swing.JButton();
        jbtAtualizarTabelaPF = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAR PRODUTOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbConsultaEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID da Empresa", "CNPJ", "Categoria", "Nome da Empresa", "Responsável", "Quantidade", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbConsultaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbConsultaEmpresaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbConsultaEmpresa);
        if (jtbConsultaEmpresa.getColumnModel().getColumnCount() > 0) {
            jtbConsultaEmpresa.getColumnModel().getColumn(0).setResizable(false);
            jtbConsultaEmpresa.getColumnModel().getColumn(0).setPreferredWidth(35);
            jtbConsultaEmpresa.getColumnModel().getColumn(1).setResizable(false);
            jtbConsultaEmpresa.getColumnModel().getColumn(2).setResizable(false);
            jtbConsultaEmpresa.getColumnModel().getColumn(3).setResizable(false);
            jtbConsultaEmpresa.getColumnModel().getColumn(4).setResizable(false);
            jtbConsultaEmpresa.getColumnModel().getColumn(5).setResizable(false);
            jtbConsultaEmpresa.getColumnModel().getColumn(5).setPreferredWidth(35);
            jtbConsultaEmpresa.getColumnModel().getColumn(6).setResizable(false);
        }

        jtfConsultaEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfConsultaEmpresaKeyReleased(evt);
            }
        });

        jcbConsultaEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Produto", "CNPJ", "Categoria", "Nome da Empresa", "Responsável", "Quantidade", "Descrição" }));

        jbtAlterarEmpresa.setText("Alterar Empresa");
        jbtAlterarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarEmpresaActionPerformed(evt);
            }
        });

        jbtAtualizarTabelaEmpresa.setText("Atualizar Tabela");
        jbtAtualizarTabelaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtualizarTabelaEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtAlterarEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAtualizarTabelaEmpresa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfConsultaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbConsultaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfConsultaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbConsultaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAlterarEmpresa)
                    .addComponent(jbtAtualizarTabelaEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpConsulta.addTab("Empresa", jPanel3);

        jtbConsultaPF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbConsultaPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbConsultaPFMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbConsultaPF);

        jcbPesquisarConsultaPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Produto", "CPF", "Nome Completo", "Quantidade", "Categoria", "Descrição" }));
        jcbPesquisarConsultaPF.setEnabled(false);

        jtfConsultaPF.setEnabled(false);
        jtfConsultaPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfConsultaPFActionPerformed(evt);
            }
        });
        jtfConsultaPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfConsultaPFKeyReleased(evt);
            }
        });

        jbtAlterarPF.setText("Alterar Empresa");
        jbtAlterarPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarPFActionPerformed(evt);
            }
        });

        jbtAtualizarTabelaPF.setText("Atualizar Tabela");
        jbtAtualizarTabelaPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtualizarTabelaPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtAlterarPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAtualizarTabelaPF))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtfConsultaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbPesquisarConsultaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfConsultaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPesquisarConsultaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAlterarPF)
                    .addComponent(jbtAtualizarTabelaPF))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtpConsulta.addTab("Pessoa Física", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpConsulta)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfConsultaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfConsultaPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfConsultaPFActionPerformed

    private void jtfConsultaEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConsultaEmpresaKeyReleased
        limparTela();
        pesquisarProdEmpresa();
    }//GEN-LAST:event_jtfConsultaEmpresaKeyReleased

    private void jbtAlterarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarEmpresaActionPerformed
        if (jtbConsultaEmpresa.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Nenhuma empresa selecionada!");
        } else {
            GUIConsultaCadEmpresa gcce = new GUIConsultaCadEmpresa();
            abrirGUIConsultaCadEmpresa();

            gcce.preencherCamposConsultaCad(cnpjAtual);
    }//GEN-LAST:event_jbtAlterarEmpresaActionPerformed
    }

    private void jtbConsultaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbConsultaEmpresaMouseClicked

        selecionarLinhaEmpresas();

    }//GEN-LAST:event_jtbConsultaEmpresaMouseClicked

    private void jbtAtualizarTabelaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtualizarTabelaEmpresaActionPerformed

        limparTela();

        PreencherTabelaEmpresas();
    }//GEN-LAST:event_jbtAtualizarTabelaEmpresaActionPerformed

    private void jbtAlterarPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarPFActionPerformed

        if (jtbConsultaPF.getSelectedRow() == -1) {

            JOptionPane.showMessageDialog(null, "Nenhuma Pessoa selecionada!");

        } else {

            GUIConsultaCadPessoaFisica gccpf = new GUIConsultaCadPessoaFisica();

            abrirGUIConsultaCadPF();

            gccpf.preencherCampos(cpfAtual);
        }

    }//GEN-LAST:event_jbtAlterarPFActionPerformed

    private void jbtAtualizarTabelaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtualizarTabelaPFActionPerformed
        limparTela();

        PreencherTabelaPessoaFisica();

    }//GEN-LAST:event_jbtAtualizarTabelaPFActionPerformed

    private void jtbConsultaPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbConsultaPFMouseClicked
        selecionarLinhaPessoaFisica();
    }//GEN-LAST:event_jtbConsultaPFMouseClicked

    private void jtfConsultaPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConsultaPFKeyReleased

    }//GEN-LAST:event_jtfConsultaPFKeyReleased
    public void abrirGUIConsultaCadPF() {

        GUIConsultaCadPessoaFisica gcpf = new GUIConsultaCadPessoaFisica();

        jdpAreaDeTrabalho.add(gcpf);

        gcpf.setVisible(true);

        gcpf.addInternalFrameListener(this);

    }

    public void abrirGUIConsultaCadEmpresa() {

        GUIConsultaCadEmpresa gce = new GUIConsultaCadEmpresa();

        jdpAreaDeTrabalho.add(gce);

        gce.setVisible(true);

        gce.addInternalFrameListener(this);

    }

    public void PreencherTabelaPessoaFisica() {

        try {

            ConPessoaFisicaDAO cDAO = new ConPessoaFisicaDAO();

            ArrayList<ProdutoPessoaFisicaVO> prod = new ArrayList<>();

            prod = cDAO.preencherTabela();

            for (int i = 0; i < prod.size(); i++) {

                dtmPessoaFisica.addRow(new String[]{
                    String.valueOf(prod.get(i).getIdProdutoPF()),
                    String.valueOf(prod.get(i).getCPF()),
                    String.valueOf(prod.get(i).getNomeCompleto()),
                    String.valueOf(prod.get(i).getQuantidade()),
                    String.valueOf(prod.get(i).getCategoria()),
                    String.valueOf(prod.get(i).getDescricao())
                });

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro ao preencher tabela pessoa física" + e.getMessage());

        }

    }

    public void PreencherTabelaEmpresas() {

        try {

            ConEmpresaDAO cDAO = new ConEmpresaDAO();

            ArrayList<ProdutoEmpresaVO> empresas = new ArrayList<>();

            empresas = cDAO.PreencherTabela();

            for (int i = 0; i < empresas.size(); i++) {
                dtmEmpresa.addRow(new String[]{
                    String.valueOf(empresas.get(i).getIdProduto()),
                    String.valueOf(empresas.get(i).getCNPJ()),
                    String.valueOf(empresas.get(i).getCategoria()),
                    String.valueOf(empresas.get(i).getNomeEmpresa()),
                    String.valueOf(empresas.get(i).getResponsavelEmpresa()),
                    String.valueOf(empresas.get(i).getQuantidade()),
                    String.valueOf(empresas.get(i).getDescricao())
                });
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro ao preencher tabela Empresa!" + e.getMessage());

        }
    }

    public void limparTela() {
        if (jtpConsulta.getSelectedIndex() == 0) {

            dtmEmpresa.setNumRows(0);

        } else {

            dtmPessoaFisica.setNumRows(0);

        }
    }

    private String cnpjAtual;

    public void selecionarLinhaEmpresas() {

        String cnpj = jtbConsultaEmpresa.getValueAt(jtbConsultaEmpresa.getSelectedRow(), 1).toString();

        this.cnpjAtual = cnpj;

    }

    private String cpfAtual;

    public void selecionarLinhaPessoaFisica() {

        String cpf = jtbConsultaPF.getValueAt(jtbConsultaPF.getSelectedRow(), 1).toString();

        this.cpfAtual = cpf;

    }

    public void pesquisarProdEmpresa() {
        try {

            if (jtfConsultaEmpresa.getText().isEmpty()) {

                limparTela();

                PreencherTabelaEmpresas();

            } else {

                String opcao = null, pesquisa = null;

                switch (jcbConsultaEmpresa.getSelectedItem().toString()) {

                    case "ID Produto":
                        opcao = "produto_id";
                        break;

                    case "CNPJ":
                        opcao = "cnpj";
                        break;

                    case "Categoria":
                        opcao = "categoria";
                        break;

                    case "Nome da Empresa":
                        opcao = "nomeEmpresa";
                        break;

                    case "Respnsável":
                        opcao = "responsavel";
                        break;

                    case "Quantidade":
                        opcao = "quantidade";
                        break;

                    case "Descrição":
                        opcao = "descricao";
                }//FIM SWITCH
                pesquisa = jtfConsultaEmpresa.getText();

                ConEmpresaDAO cDAO = new ConEmpresaDAO();

                ArrayList<ProdutoEmpresaVO> prod = new ArrayList<>();

                prod = cDAO.FiltrarProdutoEmpresa(opcao, pesquisa);

                
                for (int i = 0; i < prod.size(); i++) {
                    dtmEmpresa.addRow(new String[]{
                        String.valueOf(prod.get(i).getIdProduto()),
                        String.valueOf(prod.get(i).getCNPJ()),
                        String.valueOf(prod.get(i).getCategoria()),
                        String.valueOf(prod.get(i).getNomeEmpresa()),
                        String.valueOf(prod.get(i).getResponsavelEmpresa()),
                        String.valueOf(prod.get(i).getQuantidade()),
                        String.valueOf(prod.get(i).getDescricao())
                    });
                }
            }
            jtbConsultaEmpresa.setModel(dtmEmpresa);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro! GUIConsultaComputadores.PesquisarProdEmpresa" + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtAlterarEmpresa;
    private javax.swing.JButton jbtAlterarPF;
    private javax.swing.JButton jbtAtualizarTabelaEmpresa;
    private javax.swing.JButton jbtAtualizarTabelaPF;
    private javax.swing.JComboBox<String> jcbConsultaEmpresa;
    private javax.swing.JComboBox<String> jcbPesquisarConsultaPF;
    private javax.swing.JTable jtbConsultaEmpresa;
    private javax.swing.JTable jtbConsultaPF;
    private javax.swing.JTextField jtfConsultaEmpresa;
    private javax.swing.JTextField jtfConsultaPF;
    private javax.swing.JTabbedPane jtpConsulta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {
    }
}
