/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.CadEmpresaDAO;
import javax.swing.JOptionPane;
import model.EmpresaVO;

/**
 *
 * @author Admin
 */
public class GUIConsultaCadEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIConsultaCadEmpresa
     */
    public GUIConsultaCadEmpresa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfEmpresasNomeEmpresa = new javax.swing.JTextField();
        jtfEmpresasResponsavelEmpresa = new javax.swing.JTextField();
        jtfEmpresasCargoResponsavel = new javax.swing.JTextField();
        jtfEmpresasEmailEmpresa = new javax.swing.JTextField();
        jtfEmpresasEmailResponsavel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jftfEmpresasTelefoneEmpresa = new javax.swing.JFormattedTextField();
        jftfEmpresasTelefoneResponsavel = new javax.swing.JFormattedTextField();
        jbtAlterar = new javax.swing.JButton();
        jtfEmpresasCNPJEmpresa = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Alterar Dados da Empresa");

        jLabel2.setText("Nome da Empresa");

        jLabel3.setText("Responsavel");

        jLabel4.setText("Telefone da Empresa");

        jLabel5.setText("Cargo Hierarquico do Responsavel");

        jLabel10.setText("Email do Responsavel");

        jLabel11.setText("Email da Empresa");

        jLabel12.setText("Telefone do Responsavel");

        jLabel15.setText("CNPJ");

        try {
            jftfEmpresasTelefoneEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfEmpresasTelefoneResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jbtAlterar.setText("Alterar Empresa");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });

        jtfEmpresasCNPJEmpresa.setEditable(false);
        jtfEmpresasCNPJEmpresa.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmpresasCargoResponsavel)
                            .addComponent(jtfEmpresasEmailEmpresa)
                            .addComponent(jtfEmpresasEmailResponsavel)
                            .addComponent(jftfEmpresasTelefoneEmpresa)
                            .addComponent(jftfEmpresasTelefoneResponsavel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfEmpresasResponsavelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(jtfEmpresasNomeEmpresa)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jtfEmpresasCNPJEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jbtAlterar)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmpresasCNPJEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jbtAlterar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfEmpresasResponsavelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmpresasNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfEmpresasCargoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfEmpresasEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jftfEmpresasTelefoneEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfEmpresasEmailResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jftfEmpresasTelefoneResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    
    
    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed
        alterarEmpresa();
    }//GEN-LAST:event_jbtAlterarActionPerformed
    public void depuracao(){
          System.out.println(jtfEmpresasCNPJEmpresa.getText());
          System.out.println(jtfEmpresasEmailEmpresa.getText());
    }
    
    public void alterarEmpresa(){
        try {
            EmpresaVO eVO = new EmpresaVO();
            
            eVO.setCNPJ(jtfEmpresasCNPJEmpresa.getText());
            eVO.setNomeEmpresa(jtfEmpresasNomeEmpresa.getText());
            eVO.setResponsavelEmpresa(jtfEmpresasResponsavelEmpresa.getText());
            eVO.setCargoEmpresa(jtfEmpresasCargoResponsavel.getText());
            eVO.setEmailEmpresa(jtfEmpresasEmailEmpresa.getText());
            eVO.setTelefoneEmpresa(jftfEmpresasTelefoneEmpresa.getText());
            eVO.setEmailResponsavel(jtfEmpresasEmailResponsavel.getText());
            eVO.setTelefoneResponsavel(jftfEmpresasTelefoneResponsavel.getText());
            
            CadEmpresaDAO cDAO = new CadEmpresaDAO();
            
            cDAO.alterarDadosEmpresa(eVO);
            cDAO.alterarCadProdEmpresa(eVO);
            GUIConsultarComputadores gcc = new GUIConsultarComputadores();
            dispose();
            gcc.limparTela();
            gcc.PreencherTabelaEmpresas();
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro na aplicação! - "+e.getMessage());
        }
    }
    
    public void preencherCamposConsultaCad(String cnpj) {
        try {
            CadEmpresaDAO cDAO = new CadEmpresaDAO();
            
            EmpresaVO eVO = cDAO.preencherCamposGUIConsultaCadEmpresa(cnpj);

            jtfEmpresasNomeEmpresa.setText(eVO.getNomeEmpresa());

            jtfEmpresasResponsavelEmpresa.setText(eVO.getResponsavelEmpresa());

            jtfEmpresasCNPJEmpresa.setText(eVO.getCNPJ());

            jtfEmpresasCargoResponsavel.setText(eVO.getCargoEmpresa());

            jtfEmpresasEmailEmpresa.setText(eVO.getEmailEmpresa());

            jftfEmpresasTelefoneEmpresa.setText(eVO.getTelefoneEmpresa());

            jtfEmpresasEmailResponsavel.setText(eVO.getEmailResponsavel());

            jftfEmpresasTelefoneResponsavel.setText(eVO.getTelefoneResponsavel());
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na aplicação GUIConsultaCadProduto - " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtAlterar;
    public static javax.swing.JFormattedTextField jftfEmpresasTelefoneEmpresa;
    public static javax.swing.JFormattedTextField jftfEmpresasTelefoneResponsavel;
    public static javax.swing.JTextField jtfEmpresasCNPJEmpresa;
    public static javax.swing.JTextField jtfEmpresasCargoResponsavel;
    public static javax.swing.JTextField jtfEmpresasEmailEmpresa;
    public static javax.swing.JTextField jtfEmpresasEmailResponsavel;
    public static javax.swing.JTextField jtfEmpresasNomeEmpresa;
    public static javax.swing.JTextField jtfEmpresasResponsavelEmpresa;
    // End of variables declaration//GEN-END:variables

    void setCnpj(String cnpj) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    }
