/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.CadEmpresaDAO;
import dao.CadPessoaFisicaDAO;
import javax.swing.JOptionPane;
import model.EmpresaVO;
import model.PessoaFisicaVO;
import model.ProdutoEmpresaVO;
import model.ProdutoPessoaFisicaVO;
import utilidades.Utilidades;

/**
 *
 * @author 182320034
 */
public class GUICadastro extends javax.swing.JInternalFrame{

    /**
     * Creates new form GUICadastro
     */
    public GUICadastro() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtpCadastro = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfEmpresasNomeEmpresa = new javax.swing.JTextField();
        jtfEmpresasResponsavelEmpresa = new javax.swing.JTextField();
        jtfEmpresasCargoResponsavel = new javax.swing.JTextField();
        jtfEmpresasEmailEmpresa = new javax.swing.JTextField();
        jtfEmpresasEmailResponsavel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jftfEmpresasCNPJEmpresa = new javax.swing.JFormattedTextField();
        jftfEmpresasTelefoneEmpresa = new javax.swing.JFormattedTextField();
        jftfEmpresasTelefoneResponsavel = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfPFNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfPFEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfPFEndereco = new javax.swing.JTextField();
        jftfPFTelefone = new javax.swing.JFormattedTextField();
        jftfPFCPF = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jtfPFSobrenome = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jftfPFCEP = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jtpProdutos = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jtfProdEmpresaNomeEmpresa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfProdEmpresaResponsavel = new javax.swing.JTextField();
        jftfProdEmpresaCNPJ = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaProdEmpresaDescricaoProduto = new javax.swing.JTextArea();
        jbtProdEmpresaPesquisar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcbProdEmpresaCategoria = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jtfProdEmpresaQuantidade = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jtfProdEmpresaID = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jtfProdPFNome = new javax.swing.JTextField();
        jftfProdPFCPF = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbtnProdPFPesquisar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaProdPFDescricao = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jcbProdPFCategoria = new javax.swing.JComboBox<>();
        jtfProdPFQuantidade = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jtfProdPFID = new javax.swing.JTextField();
        jbtCadastrar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Doações");

        jLabel2.setText("Nome da Empresa");

        jLabel3.setText("Responsavel");

        jLabel4.setText("Telefone da Empresa");

        jLabel5.setText("Cargo Hierarquico do Responsavel");

        jLabel10.setText("Email do Responsavel");

        jLabel11.setText("Email da Empresa");

        jLabel12.setText("Telefone do Responsavel");

        jLabel15.setText("CNPJ");

        try {
            jftfEmpresasCNPJEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfEmpresasTelefoneEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfEmpresasTelefoneResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfEmpresasResponsavelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jtfEmpresasNomeEmpresa)
                            .addComponent(jftfEmpresasCNPJEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmpresasCargoResponsavel)
                            .addComponent(jtfEmpresasEmailEmpresa)
                            .addComponent(jtfEmpresasEmailResponsavel)
                            .addComponent(jftfEmpresasTelefoneEmpresa)
                            .addComponent(jftfEmpresasTelefoneResponsavel))))
                .addGap(325, 325, 325))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEmpresasNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfEmpresasResponsavelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jftfEmpresasCNPJEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfEmpresasCargoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfEmpresasEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jftfEmpresasTelefoneEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfEmpresasEmailResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jftfEmpresasTelefoneResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jtpCadastro.addTab("Empresas", jPanel1);

        jLabel6.setText("Nome");

        jLabel8.setText("Telefone");

        jLabel9.setText("Email");

        jLabel13.setText("CPF");

        jLabel14.setText("Endereço");

        try {
            jftfPFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfPFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel28.setText("Sobrenome");

        jLabel29.setText("CEP");

        try {
            jftfPFCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPFNome, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftfPFCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jftfPFTelefone)
                            .addComponent(jtfPFEmail)
                            .addComponent(jtfPFEndereco))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfPFSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfPFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfPFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jtfPFSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jftfPFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jftfPFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfPFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(jftfPFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jtfPFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );

        jtpCadastro.addTab("Pessoa Fisica", jPanel2);

        jLabel16.setText("Nome da Empresa");

        jtfProdEmpresaNomeEmpresa.setEditable(false);

        jLabel17.setText("Responsavel");

        jtfProdEmpresaResponsavel.setEditable(false);

        try {
            jftfProdEmpresaCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setText("CNPJ");

        jLabel21.setText("Descrição do Produto");

        jtaProdEmpresaDescricaoProduto.setColumns(20);
        jtaProdEmpresaDescricaoProduto.setRows(5);
        jScrollPane1.setViewportView(jtaProdEmpresaDescricaoProduto);

        jbtProdEmpresaPesquisar.setText("Pesquisar CNPJ");
        jbtProdEmpresaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtProdEmpresaPesquisarActionPerformed(evt);
            }
        });
        jbtProdEmpresaPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbtProdEmpresaPesquisarKeyReleased(evt);
            }
        });

        jLabel7.setText("Categoria");

        jcbProdEmpresaCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perifericos", "Computador", "Notebook" }));

        jLabel24.setText("Quantidade");

        try {
            jtfProdEmpresaQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel26.setText("ID Empresa");

        jtfProdEmpresaID.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftfProdEmpresaCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfProdEmpresaResponsavel)
                        .addComponent(jtfProdEmpresaNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(jbtProdEmpresaPesquisar))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfProdEmpresaQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcbProdEmpresaCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfProdEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel26)
                    .addComponent(jtfProdEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jftfProdEmpresaCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jcbProdEmpresaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jtfProdEmpresaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtfProdEmpresaNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jtfProdEmpresaResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtProdEmpresaPesquisar)
                        .addGap(34, 34, 34))))
        );

        jtpProdutos.addTab("Empresa", jPanel4);

        jLabel18.setText("Nome");

        jtfProdPFNome.setEditable(false);

        try {
            jftfProdPFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("CPF");

        jLabel22.setText("Descrição do Produto");

        jbtnProdPFPesquisar.setText("Pesquisar CPF");
        jbtnProdPFPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProdPFPesquisarActionPerformed(evt);
            }
        });
        jbtnProdPFPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbtnProdPFPesquisarKeyReleased(evt);
            }
        });

        jtaProdPFDescricao.setColumns(20);
        jtaProdPFDescricao.setRows(5);
        jScrollPane3.setViewportView(jtaProdPFDescricao);

        jLabel23.setText("Categoria");

        jcbProdPFCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perifericos", "Computador", "Notebook" }));

        try {
            jtfProdPFQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel25.setText("Quantidade");

        jLabel27.setText("ID Pessoa ");

        jtfProdPFID.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbProdPFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnProdPFPesquisar)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfProdPFQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jtfProdPFNome)
                            .addComponent(jftfProdPFCPF)
                            .addComponent(jtfProdPFID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfProdPFID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jftfProdPFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jtfProdPFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jtfProdPFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jcbProdPFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnProdPFPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpProdutos.addTab("Pessoa Fisica", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpProdutos)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpProdutos)
                .addContainerGap())
        );

        jtpCadastro.addTab("Produtos", jPanel3);

        jbtCadastrar.setText("Cadastrar");
        jbtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarActionPerformed(evt);
            }
        });

        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtpCadastro))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jbtCadastrar)
                .addGap(132, 132, 132)
                .addComponent(jbtLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCadastrar)
                    .addComponent(jbtLimpar))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CadProdEmpresa() {
        try {
            ProdutoEmpresaVO pVO = new ProdutoEmpresaVO();
            CadEmpresaDAO cDAO = new CadEmpresaDAO();

            pVO.setIdProdEmpresa(Integer.parseInt(jtfProdEmpresaID.getText()));

            pVO.setCNPJ(jftfProdEmpresaCNPJ.getText());

            pVO.setCategoria(jcbProdEmpresaCategoria.getSelectedItem().toString());

            pVO.setQuantidade(Integer.parseInt(jtfProdEmpresaQuantidade.getText()));

            pVO.setNomeEmpresa(jtfProdEmpresaNomeEmpresa.getText());

            pVO.setResponsavelEmpresa(jtfProdEmpresaResponsavel.getText());

            pVO.setDescricao(jtaProdEmpresaDescricaoProduto.getText());

            cDAO.CadProdEmpresa(pVO);

            JOptionPane.showMessageDialog(null, "Item cadastrado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ProdCadEmpresa! - " + e.getMessage());
        }
    }

    public void CadEmpresa() {
        try {
            EmpresaVO eVO = new EmpresaVO();

            eVO.setNomeEmpresa(jtfEmpresasNomeEmpresa.getText());

            eVO.setResponsavelEmpresa(jtfEmpresasResponsavelEmpresa.getText());

            eVO.setCNPJ(jftfEmpresasCNPJEmpresa.getText());

            eVO.setCargoEmpresa(jtfEmpresasCargoResponsavel.getText());

            eVO.setEmailEmpresa(jtfEmpresasEmailEmpresa.getText());

            eVO.setTelefoneEmpresa(jftfEmpresasTelefoneEmpresa.getText());

            eVO.setEmailResponsavel(jtfEmpresasEmailResponsavel.getText());

            eVO.setTelefoneResponsavel(jftfEmpresasTelefoneResponsavel.getText());

            long millis = System.currentTimeMillis();
            java.sql.Date data = new java.sql.Date(millis);

            eVO.setDataCadastroEmpresa(data);

            CadEmpresaDAO cDAO = new CadEmpresaDAO();

            cDAO.CadEmpresa(eVO);

            JOptionPane.showMessageDialog(null, "Cadastro Realizado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro! CadEmpresa " + e.getMessage());
        }

    }

    public void CadProdPessoaFisica() {
        try {
            ProdutoPessoaFisicaVO pVO = new ProdutoPessoaFisicaVO();

            pVO.setCPF(jftfProdPFCPF.getText());

            System.out.println("GUICPF" + pVO.getCPF());

            pVO.setNomeCompleto(jtfProdPFNome.getText());

            pVO.setQuantidade(Integer.parseInt(jtfProdPFQuantidade.getText()));

            pVO.setCategoria(jcbProdPFCategoria.getSelectedItem().toString());

            pVO.setDescricao(jtaProdPFDescricao.getText());

            pVO.setIdProdutoPF(Integer.parseInt(jtfProdPFID.getText()));

            CadPessoaFisicaDAO pDAO = new CadPessoaFisicaDAO();

            pDAO.CadProdPessoaFisicaDAO(pVO);

            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto! - " + e.getMessage());
        }

    }

    public void CadPessoaFisica() {
        try {
            PessoaFisicaVO pVO = new PessoaFisicaVO();

            pVO.setNome(jtfPFNome.getText());

            pVO.setSobrenome(jtfPFSobrenome.getText());

            pVO.setCPF(jftfPFCPF.getText());

            pVO.setTelefonePF(jftfPFTelefone.getText());

            pVO.setEmailPF(jtfPFEmail.getText());

            pVO.setEndereco(jtfPFEndereco.getText());

            pVO.setCep(jftfPFCEP.getText());

            long millis = System.currentTimeMillis();
            java.sql.Date data = new java.sql.Date(millis);

            pVO.setDataCadastroPF(data);

            CadPessoaFisicaDAO pDAO = new CadPessoaFisicaDAO();
            pDAO.CadPessoaFisicaDAO(pVO);

            JOptionPane.showMessageDialog(null, "Pessoa Física cadastrada com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro! CadPEssoaFisica -" + e.getMessage());
        }
    }

    private void jbtnProdPFPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProdPFPesquisarActionPerformed
        pesquisarPessoaFisica();
    }//GEN-LAST:event_jbtnProdPFPesquisarActionPerformed

    private void jbtProdEmpresaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtProdEmpresaPesquisarActionPerformed
        pesquisarEmpresa();
    }//GEN-LAST:event_jbtProdEmpresaPesquisarActionPerformed

    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        Utilidades util = new Utilidades();

        util.LimparCampos(jtpCadastro);

        jcbProdEmpresaCategoria.setSelectedIndex(0);

        jcbProdPFCategoria.setSelectedIndex(0);
    }//GEN-LAST:event_jbtLimparActionPerformed
    public void pesquisarPessoaFisica() {
        try {
            String cpf = jftfProdPFCPF.getText();

            PessoaFisicaVO pVO = new PessoaFisicaVO();

            CadPessoaFisicaDAO pDAO = new CadPessoaFisicaDAO();

            pVO = pDAO.PesquisarPF(cpf);

            System.out.println(pVO);

            jtfProdPFID.setText(String.valueOf(pVO.getIdPF()));

            jtfProdPFNome.setText(pVO.getNomeCompleto());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar Pessoa Física - " + e.getMessage());
        }
    }

    public void pesquisarEmpresa() {

        try {

            String cnpj = jftfProdEmpresaCNPJ.getText();

            CadEmpresaDAO cDAO = new CadEmpresaDAO();

            EmpresaVO eVO = new EmpresaVO();

            eVO = cDAO.buscarEmpresa(cnpj);

            if (eVO.getIdEmpresa() == 0) {

                JOptionPane.showMessageDialog(null, "Não foram encontrados registros para esse CNPJ");

            } else {

                jtfProdEmpresaID.setText(String.valueOf(eVO.getIdEmpresa()));

                jtfProdEmpresaNomeEmpresa.setText(eVO.getNomeEmpresa());

                jtfProdEmpresaResponsavel.setText(eVO.getResponsavelEmpresa());

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro ao pesquisar empresa! - " + e.getMessage());

        }
    }


    private void jbtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarActionPerformed

        int pagina = jtpCadastro.getSelectedIndex();

        Utilidades util = new Utilidades();

        switch (pagina) {
            case 0:

                if (jtfEmpresasNomeEmpresa.getText().isEmpty() || jtfEmpresasResponsavelEmpresa.getText().isEmpty() || jftfEmpresasCNPJEmpresa.getText().isEmpty() || jtfEmpresasCargoResponsavel.getText().isEmpty() || jtfEmpresasEmailEmpresa.getText().isEmpty() || jftfEmpresasTelefoneEmpresa.getText().isEmpty() || jtfEmpresasEmailResponsavel.getText().isEmpty() || jftfEmpresasTelefoneResponsavel.getText().isEmpty()) {

                    JOptionPane.showMessageDialog(null, "Por Favor, preencha os campos corretamente!");

                } else {

                    CadEmpresa();

                    util.limparTela(jtpCadastro);
                }

                break;

            case 1:

                if (jtfPFNome.getText().isEmpty() || jftfPFCPF.getText().isEmpty() || jftfPFTelefone.getText().isEmpty() || jtfPFEmail.getText().isEmpty() || jtfPFEndereco.getText().isEmpty()) {

                    JOptionPane.showMessageDialog(null, "Por Favor, preencha os campos corretamente!");

                } else {

                    CadPessoaFisica();

                    util.limparTela(jtpCadastro);

                }

                break;

            case 2:

                if (jtpProdutos.getSelectedIndex() == 0) {

                    if (jftfProdEmpresaCNPJ.getText().isEmpty() || jtfProdEmpresaQuantidade.getText().isEmpty() || jtfProdEmpresaNomeEmpresa.getText().isEmpty() || jtfProdEmpresaResponsavel.getText().isEmpty() || jtaProdEmpresaDescricaoProduto.getText().isEmpty()) {

                        JOptionPane.showMessageDialog(null, "Por Favor, preencha os campos corretamente!");

                    } else {

                        CadProdEmpresa();

                        util.limparTela(jtpCadastro);
                    }

                } else {

                    if (jtfProdPFNome.getText().isEmpty() || jftfProdPFCPF.getText().isEmpty() || jtfProdPFQuantidade.getText().isEmpty() || jtaProdPFDescricao.getText().isEmpty()) {

                        JOptionPane.showMessageDialog(null, "Por Favor, preencha os campos corretamente!");

                    } else {

                        CadProdPessoaFisica();

                        util.limparTela(jtpCadastro);
                   
                    }
                }

        }


    }//GEN-LAST:event_jbtCadastrarActionPerformed

    private void jbtnProdPFPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnProdPFPesquisarKeyReleased

    }//GEN-LAST:event_jbtnProdPFPesquisarKeyReleased

    private void jbtProdEmpresaPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtProdEmpresaPesquisarKeyReleased

    }//GEN-LAST:event_jbtProdEmpresaPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtCadastrar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtProdEmpresaPesquisar;
    private javax.swing.JButton jbtnProdPFPesquisar;
    private javax.swing.JComboBox<String> jcbProdEmpresaCategoria;
    private javax.swing.JComboBox<String> jcbProdPFCategoria;
    private javax.swing.JFormattedTextField jftfEmpresasCNPJEmpresa;
    private javax.swing.JFormattedTextField jftfEmpresasTelefoneEmpresa;
    private javax.swing.JFormattedTextField jftfEmpresasTelefoneResponsavel;
    private javax.swing.JFormattedTextField jftfPFCEP;
    private javax.swing.JFormattedTextField jftfPFCPF;
    private javax.swing.JFormattedTextField jftfPFTelefone;
    private javax.swing.JFormattedTextField jftfProdEmpresaCNPJ;
    private javax.swing.JFormattedTextField jftfProdPFCPF;
    private javax.swing.JTextArea jtaProdEmpresaDescricaoProduto;
    private javax.swing.JTextArea jtaProdPFDescricao;
    private javax.swing.JTextField jtfEmpresasCargoResponsavel;
    private javax.swing.JTextField jtfEmpresasEmailEmpresa;
    private javax.swing.JTextField jtfEmpresasEmailResponsavel;
    private javax.swing.JTextField jtfEmpresasNomeEmpresa;
    private javax.swing.JTextField jtfEmpresasResponsavelEmpresa;
    private javax.swing.JTextField jtfPFEmail;
    private javax.swing.JTextField jtfPFEndereco;
    private javax.swing.JTextField jtfPFNome;
    private javax.swing.JTextField jtfPFSobrenome;
    private javax.swing.JTextField jtfProdEmpresaID;
    private javax.swing.JTextField jtfProdEmpresaNomeEmpresa;
    private javax.swing.JFormattedTextField jtfProdEmpresaQuantidade;
    private javax.swing.JTextField jtfProdEmpresaResponsavel;
    private javax.swing.JTextField jtfProdPFID;
    private javax.swing.JTextField jtfProdPFNome;
    private javax.swing.JFormattedTextField jtfProdPFQuantidade;
    private javax.swing.JTabbedPane jtpCadastro;
    private javax.swing.JTabbedPane jtpProdutos;
    // End of variables declaration//GEN-END:variables
}
