/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author 182320034
 */
public class GUIPrincipal extends javax.swing.JFrame implements InternalFrameListener {

    private boolean flagGUICadastro, flagGUIColaboradores, flagGUIConsultaComputador, flagGUIConsultaCadEmpresa, flagGUILogin, flagGUICadUsuarios;

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();

        setExtendedState(MAXIMIZED_BOTH);

    }

    public void verificarUsuario(String usuario) {

        //Pega o usuário logado na tela GUILogin
        jlbUsuario.setText(usuario);

    }

    public void abrirGUIColaboradores() {
        if (!flagGUIColaboradores) {
            //Função para abrir GUIColaboradores
            GUIConsultaColaboradores gcc = new GUIConsultaColaboradores();

            jdpAreaDeTrabalho.add(gcc);
            gcc.setVisible(true);
            flagGUIColaboradores = true;
            gcc.addInternalFrameListener(this);

        }
    }

    public void abrirGUICadUsuarios() {
        if (!flagGUICadUsuarios) {
            //Função para abrir GUICadUsuarios
            GUICadUsuarios gcu = new GUICadUsuarios();

            jdpAreaDeTrabalho.add(gcu);

            gcu.setVisible(true);

            flagGUICadUsuarios = true;

            gcu.addInternalFrameListener(this);

        }
    }

    public void abrirGUIConsultaCadEmpresa() {
        if (!flagGUIConsultaCadEmpresa) {
            //Função para abrir GUIConsultaCadEmpresas
            GUIConsultaCadEmpresa gce = new GUIConsultaCadEmpresa();

            jdpAreaDeTrabalho.add(gce);

            gce.setVisible(true);

            flagGUIConsultaCadEmpresa = true;

            gce.addInternalFrameListener(this);

        }
    }

    public void abrirGUIConsultaComputador() {
        if (!flagGUIConsultaComputador) {
            //Função para abrir GUIConsultaComputadores
            GUIConsultarComputadores gcc = new GUIConsultarComputadores();

            jdpAreaDeTrabalho.add(gcc);

            gcc.setVisible(true);

            flagGUIConsultaComputador = true;

            gcc.addInternalFrameListener(this);

        }
    }

    private void abrirGUICadProdutos() {
        if (!flagGUICadastro) {
            //Função para abrir GUICadProdutos
            GUICadastro gc = new GUICadastro();

            jdpAreaDeTrabalho.add(gc);

            gc.setVisible(true);

            flagGUICadastro = true;

            gc.addInternalFrameListener(this);

        }
    }

    public void logoff() {
        if (!flagGUILogin) {
            //Função para fechar a GUIPrincipal e abrir GUILogin
            GUILogin gl = new GUILogin();

            gl.setVisible(true);

            flagGUILogin = true;

            dispose();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jlbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmLogoff = new javax.swing.JMenu();
        jmiLogoff = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jmCadastro = new javax.swing.JMenu();
        jmiCadDoacao = new javax.swing.JMenuItem();
        jmiCadUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiConsultaComputador = new javax.swing.JMenuItem();
        jmiColaboradores = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pids_Tech");
        setName("Pids_Tech"); // NOI18N

        jdpAreaDeTrabalho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jlbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbUsuario.setText("NULL");
        jlbUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlbUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jmLogoff.setText("Sair");
        jmLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLogoffActionPerformed(evt);
            }
        });

        jmiLogoff.setText("Logoff");
        jmiLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoffActionPerformed(evt);
            }
        });
        jmLogoff.add(jmiLogoff);

        jmiSair.setText("Sair do Programa");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmLogoff.add(jmiSair);

        jMenuBar1.add(jmLogoff);

        jmCadastro.setText("Cadastro");
        jmCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroActionPerformed(evt);
            }
        });

        jmiCadDoacao.setText("Cadastro Doações");
        jmiCadDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadDoacaoActionPerformed(evt);
            }
        });
        jmiCadDoacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiCadDoacaoKeyPressed(evt);
            }
        });
        jmCadastro.add(jmiCadDoacao);

        jmiCadUsuario.setText("Cadastro de Usuarios");
        jmiCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadUsuarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadUsuario);

        jMenuBar1.add(jmCadastro);

        jMenu2.setText("Consulta");

        jmiConsultaComputador.setText("Computadores");
        jmiConsultaComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaComputadorActionPerformed(evt);
            }
        });
        jMenu2.add(jmiConsultaComputador);

        jmiColaboradores.setText("Colaboradores");
        jmiColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiColaboradoresActionPerformed(evt);
            }
        });
        jMenu2.add(jmiColaboradores);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpAreaDeTrabalho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastroActionPerformed

    private void jmiCadDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadDoacaoActionPerformed
        abrirGUICadProdutos();
    }//GEN-LAST:event_jmiCadDoacaoActionPerformed

    private void jmiCadDoacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiCadDoacaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCadDoacaoKeyPressed

    private void jmiConsultaComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaComputadorActionPerformed
        abrirGUIConsultaComputador();
    }//GEN-LAST:event_jmiConsultaComputadorActionPerformed

    private void jmLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLogoffActionPerformed
        JOptionPane.showMessageDialog(null, "Fazendo Logoff");
    }//GEN-LAST:event_jmLogoffActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoffActionPerformed
        UIManager.put("OptionPane.yesButtonText", "Fazer Logoff");

        UIManager.put("OptionPane.noButtonText", "Cancelar");

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja Realmente fazer Logoff?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (resposta == JOptionPane.YES_OPTION) {

            logoff();

        }

    }//GEN-LAST:event_jmiLogoffActionPerformed

    private void jmiCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadUsuarioActionPerformed
        abrirGUICadUsuarios();
    }//GEN-LAST:event_jmiCadUsuarioActionPerformed

    private void jmiColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiColaboradoresActionPerformed
        abrirGUIColaboradores();
    }//GEN-LAST:event_jmiColaboradoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JDesktopPane jdpAreaDeTrabalho;
    public static javax.swing.JLabel jlbUsuario;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmLogoff;
    private javax.swing.JMenuItem jmiCadDoacao;
    public static javax.swing.JMenuItem jmiCadUsuario;
    private javax.swing.JMenuItem jmiColaboradores;
    private javax.swing.JMenuItem jmiConsultaComputador;
    private javax.swing.JMenuItem jmiLogoff;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        if (ife.getInternalFrame() instanceof GUICadastro) {
            flagGUICadastro = false;
        }
        if (ife.getInternalFrame() instanceof GUIConsultarComputadores) {
            flagGUIConsultaComputador = false;
        }
        if (ife.getInternalFrame() instanceof GUICadUsuarios) {
            flagGUICadUsuarios = false;
        }
        if (ife.getInternalFrame()instanceof GUIConsultaColaboradores) {
            flagGUIColaboradores = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {

    }
}
